# -*- coding: utf-8 -*-
"""
/***************************************************************************
 OASdglDatachecker
                                 A QGIS plugin
 This plugin checks data of sewersystems for local goverment
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-06-24
        copyright            : (C) 2019 by OAS De Grote Lucht
        email                : svanderhoeven@hhdelfland.nl
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load OASdglDatachecker class from file OASdglDatachecker.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Datachecker import OASdglDatachecker
    return OASdglDatachecker(iface)
